import type { Metadata } from "next";
import "../../tailwind.scss";
import "./globals.css";
import AppBarHeader from "./components/AppBar";
import Providers from "./providers";
import { NextIntlClientProvider } from "next-intl";
import { SnackbarProvider } from "./components/snackbar-provider";

export const metadata: Metadata = {
  title: "Nidhogg",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sv">
      <body>
        <Providers>
          <NextIntlClientProvider>
            <SnackbarProvider />
            <AppBarHeader />
            {children}
          </NextIntlClientProvider>
        </Providers>
      </body>
    </html>
  );
}