import type { Metadata } from "next";
import { theme } from "@/theme";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import AppBarHeader from "./components/AppBar";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Nidhogg",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <Providers>
          <ThemeProvider theme={theme}>
            <AppBarHeader />
            {children}
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
